version: "3.7"

services:
  db:
    image: postgres:14.1-alpine3.14
    volumes:
      - data:/var/lib/postgresql/data
    env_file: ./.env.local
    ports:
      - "5432:5432"

  db-test:
    image: postgres:14.1-alpine3.14
    env_file: ./.env.test.local
    ports:
      - 5433:5432

volumes:
  data:
